# Generated by Django 4.2 on 2023-04-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=7)),
                ('release_date', models.CharField(max_length=10)),
                ('lte_exists', models.CharField(max_length=5)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
